filetype off

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'tpope/vim-surround'
Plugin 'easymotion/vim-easymotion'
call vundle#end()

let g:ycm_extra_conf_globlist = ['~/devel/*/*','!~/*']
let g:ycm_filetype_whitelist = {'cpp':1, 'c':1, 'python':1}

filetype plugin indent on
set autoindent
set noexpandtab

syntax on
let &colorcolumn="80,".join(range(100,999),",")
highlight ColorColumn ctermbg=darkgray

