.TH ATMOST 1 "2019-07-16" "Limits concurrent execution of executable."
.SH "NAME"
atmost \- tool for limiting the concurrent execution of a specified executable(s).
.SH "SYNOPSIS"
.SY atmost
[
OPTIONS
] [-- EXECUTABLE [ARGS...]]
.YS
.SH "DESCRIPTION"
The \fIatmost\fR utility allows to limit concurrent execution of a single
executable or a set of executables, depending on various criteria like
CPU load, memory and swap usage, thermal zone temeratures, current number
of I/O operations, etc. or just by a simple maximum number.

.SH "OPTIONS"
.SS "General options"
.TP
\fB-h\fR, \fB--help\fR
Show this help message and exit.
.TP
\fB-v\fR, \fB--verbose\fR
Make output more verbose. Can be specified multiple times, each instance
increases the verbosity level.
.TP
\fB-f\fR \fIFILE-PATH\fR
Without this option \fBatmost\fR uses the real path of \fIEXECUTABLE\fR
to determine the number of concurrent running instances of the executable.
If the -f option is specified, then FILE-PATH is used instead as a token
used to count concurrent processes. This means that different executables
may be subject of a single counter. FILE-PATH must be a path to an existing
file.
.TP
\fB-r\fR 
Reset the instance counter associated with \fIEXECUTABLE\fR or with the
\fIFILE-PATH\fR specified after the -f option.

.SS "Execution limits"
.TP
\fB-n\fR \fICOUNT\fR
Limit the number of instances of \fIEXECUTABLE\fR to at most the value of COUNT.
COUNT must be a positive integer.
.TP
\fB-l\fR \fIPERCENT\fR
Wait before starting a new instance of \fIEXECUTABLE\fR while 1 minute average
CPU load is over the value of PERCENT. PERCENT must be a positive floating-point
value,
.TP
\fB-L\fR \fIPERCENT\fR
Wait before starting a new instance of \fIEXECUTABLE\fR while 5 minute average
CPU load is over the value of PERCENT. PERCENT must be a positive floating-point
value.
.TP
\fB-m\fR \fIPERCENT\fR
Wait before starting a new instance of \fIEXECUTABLE\fR while current amount
of available memory is lower than the value of PERCENT. PERCENT must be
a positive floating-point value.
.TP
\fB-M\fR \fIPERCENT\fR
Wait before starting a new instance of \fIEXECUTABLE\fR while current amount
of free memory is lower than the value of PERCENT. PERCENT must be
a positive floating-point value.
.TP
\fB-S\fR \fIPERCENT\fR
Wait before starting a new instance of \fIEXECUTABLE\fR while current amount
of free swap space is lower than the value of PERCENT. PERCENT must be
a positive floating-point value.
.TP
\fB-p\fR \fICOUNT\fR
Wait before starting a new instance of \fIEXECUTABLE\fR while current number
of all processes exceeds the value of COUNT.
COUNT must be a positive integer.
.TP
\fB-tc\fR \fITEMP\fR
Wait before starting a new instance of \fIEXECUTABLE\fR while current CPU
thermal zone temperature exceeds the value of TEMP.
.TP
\fB-tg\fR \fITEMP\fR
Wait before starting a new instance of \fIEXECUTABLE\fR while current GPU
thermal zone temperature exceeds the value of TEMP.
.TP
\fB-tb\fR \fITEMP\fR
Wait before starting a new instance of \fIEXECUTABLE\fR while current BAT
(battery) thermal zone temperature exceeds the value of TEMP.
.TP
\fB-io\fR \fICOUNT\fR
Wait before starting a new instance of \fIEXECUTABLE\fR while current number
of I/O operations exceeds the value of TEMP.
.TP
\fB-nw\fR \fIN\fR
Wait before starting a new instance of \fIEXECUTABLE\fR while current combined
rated speed in MB/s of all network interfaces is less than the value of N.

.SS "Other limits"

.TP
\fB-snw\fR \fIN\fR
Specifies the total rated speed in MB/s of all network connections that
is considered \(lqslow\(rq for the purpose of the limit modifier options.

.SS "Limit modifiers"
The following arguents may be specified after the \fBExecution limit\fR
arguments to modify the value of the limit under specified circumstances,
for example the machine running on battery, running without a network connection,
etc.

.TP
\fB-batt\fR \fIMOD\fR
Change the value of the preceding \fBExecution limit\fR by the value
of \fIMOD\fR in case that the machine is running on battery.

.TP
\fB-slnw\fR \fIMOD\fR
Change the value of the preceding \fBExecution limit\fR by the value
of \fIMOD\fR in case that the current combined rated speed of all network
interfaces is less than the limit specified by the \fB-snw\fR option.

.TP
\fB-nonw\fR \fIMOD\fR
Change the value of the preceding \fBExecution limit\fR by the value
of \fIMOD\fR in case that there is no network connection.

.SH "EXAMPLES"

.SH "AUTHOR"
Matus Chochlik, chochlik@gmail.com
.SH "COPYRIGHT"
Copyright (c) 2019 Matus Chochlik
.PP
Permission is granted to copy, distribute and/or modify this document
under the terms of the Boost Software License, Version 1.0.
(See a copy at http://www.boost.org/LICENSE_1_0.txt)
