#!/usr/bin/python3
# coding: UTF-8
#  Copyright (c) 2019 Matus Chochlik

import os
import sys
import errno
import shutil
import getpass
import logging
import hashlib
import tempfile
import subprocess

# ------------------------------------------------------------------------------
class ClangTidyCacheOpts(object):
    # --------------------------------------------------------------------------
    def __init__(self, log, args):
        self._original_args = args
        self._clang_tidy_args = None
        self._compiler_args = None

        for i in range(len(args)):
            if args[i] == "--":
                self._clang_tidy_args = args[:i]
                self._compiler_args = args[i+1:]

        if self._compiler_args:
            for i in range(1, len(self._compiler_args)):
                if self._compiler_args[i-1] in ["-o", "--output"]:
                    self._compiler_args[i] = "-"
                if self._compiler_args[i-1] in ["-c"]:
                    self._compiler_args[i-1] = "-E"

    # --------------------------------------------------------------------------
    def should_print_dir(self):
        return self._original_args[0] == "--cache-dir"
    # --------------------------------------------------------------------------
    def should_remove_dir(self):
        return self._original_args[0] == "--clean"
    # --------------------------------------------------------------------------
    def original_args(self):
        return self._original_args
    # --------------------------------------------------------------------------
    def clang_tidy_args(self):
        return self._clang_tidy_args
    # --------------------------------------------------------------------------
    def compiler_args(self):
        return self._compiler_args
    # --------------------------------------------------------------------------
    def cache_dir(self):
        return os.getenv(
            "CTCACHE_DIR",
            os.path.join(
                tempfile.tempdir if tempfile.tempdir else "/tmp",
                "ctcache-"+getpass.getuser()
            )
        )

# ------------------------------------------------------------------------------
def hash_inputs(opts):
    co_args = opts.compiler_args()
    ct_args = opts.compiler_args()
    if not co_args and not ct_args:
        return None

    result = hashlib.sha1()

    proc = subprocess.Popen(
        co_args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    stdout, stderr = proc.communicate()
    if stderr: return None

    result.update(stdout)

    for arg in co_args:
        result.update(arg.encode("utf8"))
    for arg in ct_args:
        result.update(arg.encode("utf8"))

    return result.hexdigest()
# ------------------------------------------------------------------------------
def mkdir_p(path):
    try: os.makedirs(path)
    except OSError as os_error:
        if os_error.errno == errno.EEXIST and os.path.isdir(path): pass
        else: raise
# ------------------------------------------------------------------------------
def make_path(opts, digest):
    return os.path.join(
        opts.cache_dir(),
        digest[:2],
        digest[2:]
    )
# ------------------------------------------------------------------------------
def is_cached(opts, digest):
    return os.path.isfile(make_path(opts, digest))
# ------------------------------------------------------------------------------
def store_in_cache(opts, digest):
    p = make_path(opts, digest)
    mkdir_p(os.path.dirname(p))
    open(p, "w").close()
# ------------------------------------------------------------------------------
def run_clang_tidy_cached(log, opts):
    digest = None
    try:
        digest = hash_inputs(opts)
        if digest:
            if is_cached(opts, digest):
                return 0
    except Exception as error:
        log.error(str(error))

    result = subprocess.call(opts.original_args())

    if result == 0 and digest:
        try: store_in_cache(opts, digest)
        except Exception as error:
            log.error(str(error))

    return result
# ------------------------------------------------------------------------------
def main():
    log = logging.getLogger(os.path.basename(__file__))
    try:
        opts = ClangTidyCacheOpts(log, sys.argv[1:])
        if opts.should_print_dir():
            print(opts.cache_dir())
        elif opts.should_remove_dir():
            import shutil
            shutil.rmtree(opts.cache_dir())
        else:
            return run_clang_tidy_cached(log, opts)
        return 0
    except Exception as error:
        log.error(str(error))
        return 1
# ------------------------------------------------------------------------------
if __name__ == "__main__":
    sys.exit(main())
